/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { EtherTransfer, EtherTransferInterface } from "../EtherTransfer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "sendEther",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101b08061001f6000396000f3fe6080604052600436106100225760003560e01c8063c1756a2c1461002e57600080fd5b3661002957005b600080fd5b34801561003a57600080fd5b5061004e610049366004610142565b610050565b005b804710156100a55760405162461bcd60e51b815260206004820181905260248201527f496e73756666696369656e742062616c616e636520696e20636f6e747261637460448201526064015b60405180910390fd5b6000826001600160a01b03168260405160006040518083038185875af1925050503d80600081146100f2576040519150601f19603f3d011682016040523d82523d6000602084013e6100f7565b606091505b505090508061013d5760405162461bcd60e51b81526020600482015260126024820152711d1c985b9cd858dd1a5bdb8819985a5b195960721b604482015260640161009c565b505050565b6000806040838503121561015557600080fd5b82356001600160a01b038116811461016c57600080fd5b94602093909301359350505056fea2646970667358221220d8edaaf74277db837922aa033457b04ca6af4bba48217eedbef9c4432f895e2d64736f6c634300081c0033";

type EtherTransferConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EtherTransferConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EtherTransfer__factory extends ContractFactory {
  constructor(...args: EtherTransferConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EtherTransfer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EtherTransfer__factory {
    return super.connect(runner) as EtherTransfer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EtherTransferInterface {
    return new Interface(_abi) as EtherTransferInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EtherTransfer {
    return new Contract(address, _abi, runner) as unknown as EtherTransfer;
  }
}
